//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qw5Entities : DbContext
    {
        public qw5Entities(string connectionStringName)
            : base($"name={connectionStringName}")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Виды_пикетов> Виды_пикетов { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Заказчик> Заказчик { get; set; }
        public virtual DbSet<Измерительное_оборудование> Измерительное_оборудование { get; set; }
        public virtual DbSet<Квалификация> Квалификация { get; set; }
        public virtual DbSet<Координаты_точки> Координаты_точки { get; set; }
        public virtual DbSet<Методика> Методика { get; set; }
        public virtual DbSet<Обработки_на_профиле> Обработки_на_профиле { get; set; }
        public virtual DbSet<Пикет> Пикет { get; set; }
        public virtual DbSet<Пикет_ИзмерительноеОборудование> Пикет_ИзмерительноеОборудование { get; set; }
        public virtual DbSet<Пикет_ПромежуточныеИзмерения> Пикет_ПромежуточныеИзмерения { get; set; }
        public virtual DbSet<Пикет_ПромежуточныеТрансформантыИзмерения> Пикет_ПромежуточныеТрансформантыИзмерения { get; set; }
        public virtual DbSet<Пикет_Сотрудники> Пикет_Сотрудники { get; set; }
        public virtual DbSet<Пикет_ТрансформантаИзмерения> Пикет_ТрансформантаИзмерения { get; set; }
        public virtual DbSet<Площадь> Площадь { get; set; }
        public virtual DbSet<Площадь_УглыПериметра> Площадь_УглыПериметра { get; set; }
        public virtual DbSet<Проект> Проект { get; set; }
        public virtual DbSet<Профиль> Профиль { get; set; }
        public virtual DbSet<Профиль_СписокОбработок> Профиль_СписокОбработок { get; set; }
        public virtual DbSet<Профиль_ТелеметрическиеИзмерения> Профиль_ТелеметрическиеИзмерения { get; set; }
        public virtual DbSet<Профиль_ТочкиИзломов> Профиль_ТочкиИзломов { get; set; }
        public virtual DbSet<Профиль_ЭлектромагнитныеИзмерения> Профиль_ЭлектромагнитныеИзмерения { get; set; }
        public virtual DbSet<Результаты_измерения> Результаты_измерения { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Список_фильтров_над_обработкой> Список_фильтров_над_обработкой { get; set; }
        public virtual DbSet<Телеметрические_измерения> Телеметрические_измерения { get; set; }
        public virtual DbSet<Трансформанта_измерения> Трансформанта_измерения { get; set; }
        public virtual DbSet<Фильтры_обработок> Фильтры_обработок { get; set; }
        public virtual DbSet<Электромагнитные_измерения> Электромагнитные_измерения { get; set; }
    }
}
