//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Методика
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Методика()
        {
            this.Профиль = new HashSet<Профиль>();
        }
    
        public int id { get; set; }
        public string название_методики { get; set; }
        public Nullable<int> id_генератора_установки { get; set; }
        public Nullable<int> id_измерительной_установки { get; set; }
        public Nullable<int> id_телеметрической_установки { get; set; }
        public Nullable<double> максимальная_скорость_БПЛА { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
        public Nullable<bool> удален { get; set; }
    
        public virtual Измерительное_оборудование Измерительное_оборудование { get; set; }
        public virtual Измерительное_оборудование Измерительное_оборудование1 { get; set; }
        public virtual Измерительное_оборудование Измерительное_оборудование2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль> Профиль { get; set; }
    }
}
