//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пикет_ПромежуточныеИзмерения
    {
        public int id { get; set; }
        public Nullable<int> id_пикета { get; set; }
        public Nullable<int> id_результатов_измерения { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
        public Nullable<bool> удален { get; set; }
    
        public virtual Пикет Пикет { get; set; }
        public virtual Результаты_измерения Результаты_измерения { get; set; }
    }
}
