//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Площадь
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Площадь()
        {
            this.Площадь_УглыПериметра = new HashSet<Площадь_УглыПериметра>();
            this.Профиль = new HashSet<Профиль>();
        }
    
        public int id { get; set; }
        public string название { get; set; }
        public Nullable<int> id_проекта { get; set; }
        public Nullable<int> id_супервайзера_полевых_работ { get; set; }
        public Nullable<int> id_супервайзера_обработки_данных { get; set; }
        public Nullable<double> длина_периметра { get; set; }
        public Nullable<double> площадь_периметра { get; set; }
        public Nullable<System.DateTime> дата_начала_работ { get; set; }
        public Nullable<System.DateTime> дата_окончания_работ { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
        public Nullable<bool> удален { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Площадь_УглыПериметра> Площадь_УглыПериметра { get; set; }
        public virtual Проект Проект { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Сотрудник Сотрудник1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль> Профиль { get; set; }
    }
}
