//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Профиль
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Профиль()
        {
            this.Пикет = new HashSet<Пикет>();
            this.Профиль_СписокОбработок = new HashSet<Профиль_СписокОбработок>();
            this.Профиль_ТелеметрическиеИзмерения = new HashSet<Профиль_ТелеметрическиеИзмерения>();
            this.Профиль_ТочкиИзломов = new HashSet<Профиль_ТочкиИзломов>();
            this.Профиль_ЭлектромагнитныеИзмерения = new HashSet<Профиль_ЭлектромагнитныеИзмерения>();
        }
    
        public int id { get; set; }
        public string название_профиля { get; set; }
        public Nullable<int> id_координат_начала { get; set; }
        public Nullable<int> Id_координат_конца { get; set; }
        public Nullable<int> id_площади { get; set; }
        public Nullable<int> id_методики { get; set; }
        public Nullable<double> длина_профиля { get; set; }
        public Nullable<System.DateTime> дата_начала_работ { get; set; }
        public Nullable<System.DateTime> дата_окончания_работ { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
        public Nullable<bool> удален { get; set; }
    
        public virtual Координаты_точки Координаты_точки { get; set; }
        public virtual Координаты_точки Координаты_точки1 { get; set; }
        public virtual Методика Методика { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пикет> Пикет { get; set; }
        public virtual Площадь Площадь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль_СписокОбработок> Профиль_СписокОбработок { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль_ТелеметрическиеИзмерения> Профиль_ТелеметрическиеИзмерения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль_ТочкиИзломов> Профиль_ТочкиИзломов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль_ЭлектромагнитныеИзмерения> Профиль_ЭлектромагнитныеИзмерения { get; set; }
    }
}
