//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Convertor.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Пикет_Сотрудники = new HashSet<Пикет_Сотрудники>();
            this.Площадь = new HashSet<Площадь>();
            this.Площадь1 = new HashSet<Площадь>();
            this.Профиль_СписокОбработок = new HashSet<Профиль_СписокОбработок>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_должности { get; set; }
        public Nullable<int> id_квалификации { get; set; }
        public Nullable<int> опыт_работы_в_коллективе { get; set; }
        public Nullable<int> опят_работы_по_специальности { get; set; }
        public Nullable<System.DateTime> дата_прохождения_медосмотра { get; set; }
        public Nullable<System.DateTime> дата_добавления_записи { get; set; }
        public Nullable<System.DateTime> дата_последнего_изменения_записи { get; set; }
        public Nullable<bool> удален { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual Квалификация Квалификация { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пикет_Сотрудники> Пикет_Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Площадь> Площадь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Площадь> Площадь1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Профиль_СписокОбработок> Профиль_СписокОбработок { get; set; }
    }
}
